// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("academic_year");

                    b.Property<DateTime>("AnnouncementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("announcement_date");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("deadline");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("program_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProgramId");

                    b.ToTable("admissions", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.AdmissionExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("admission_id");

                    b.Property<DateTime>("ExamDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("exam_date_time");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.ToTable("admission_exams", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.AdmissionExamTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AdmissionExamId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("admission_exam_id");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("exam_name");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("AdmissionExamId", "LanguageId")
                        .IsUnique();

                    b.ToTable("admission_exam_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.AdmissionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("admission_id");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("media_id");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("result_type");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("MediaId");

                    b.ToTable("admission_results", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("author");

                    b.Property<Guid>("CoverImageMediaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cover_image_media_id");

                    b.Property<Guid>("FileMediaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("file_media_id");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("isbn");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int")
                        .HasColumnName("publication_year");

                    b.HasKey("Id");

                    b.HasIndex("CoverImageMediaId");

                    b.HasIndex("FileMediaId");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.BookTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("book_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("BookId", "LanguageId")
                        .IsUnique();

                    b.ToTable("book_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.CategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("CategoryId", "LanguageId")
                        .IsUnique();

                    b.ToTable("category_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("course_code");

                    b.Property<Guid>("CourseGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_group_id");

                    b.Property<decimal>("Credits")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("credits");

                    b.Property<int>("PracticalHours")
                        .HasColumnType("int")
                        .HasColumnName("practical_hours");

                    b.Property<int>("TheoreticalHours")
                        .HasColumnType("int")
                        .HasColumnName("theoretical_hours");

                    b.HasKey("Id");

                    b.HasIndex("CourseGroupId");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.CourseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CourseGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("course_groub_code");

                    b.HasKey("Id");

                    b.ToTable("course_groups", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.CourseGroupTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_group_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("CourseGroupId", "LanguageId")
                        .IsUnique();

                    b.ToTable("course_group_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.CourseTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("CourseId", "LanguageId")
                        .IsUnique();

                    b.ToTable("course_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int")
                        .HasColumnName("academic_year");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<string>("CourseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("course_type");

                    b.Property<int>("Semester")
                        .HasColumnType("int")
                        .HasColumnName("semester");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("specialization_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("curriculum", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<Guid>("FaqCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("faq_category_id");

                    b.HasKey("Id");

                    b.HasIndex("FaqCategoryId");

                    b.ToTable("faqs", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.FaqCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("faq_categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.FaqCategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("FaqCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("faq_category_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("FaqCategoryId", "LanguageId")
                        .IsUnique();

                    b.ToTable("faq_category_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.FaqTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<Guid>("FaqId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("faq_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("FaqId", "LanguageId")
                        .IsUnique();

                    b.ToTable("faq_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("location_code");

                    b.HasKey("Id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.LocationTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LocationId", "LanguageId")
                        .IsUnique();

                    b.ToTable("location_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("file_type");

                    b.Property<Guid>("MediaCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("media_category_id");

                    b.HasKey("Id");

                    b.HasIndex("MediaCategoryId");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.MediaCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("media_categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.MediaCategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<Guid>("MediaCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("media_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MediaCategoryId", "LanguageId")
                        .IsUnique();

                    b.ToTable("media_category_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("location");

                    b.HasKey("Id");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("LinkURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("link_url");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("menu_id");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.MenuItemTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("menu_item_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MenuItemId", "LanguageId")
                        .IsUnique();

                    b.ToTable("menu_item_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.PageTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("page_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PageId", "LanguageId")
                        .IsUnique();

                    b.ToTable("page_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("publication_date");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.PostTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("post_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PostId", "LanguageId")
                        .IsUnique();

                    b.ToTable("post_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("duration");

                    b.HasKey("Id");

                    b.ToTable("programs", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.ProgramTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("program_id");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProgramId", "LanguageId")
                        .IsUnique();

                    b.ToTable("program_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Slider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("LinkURL")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("link_url");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("media_id");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("sliders", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.SliderTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<Guid>("SliderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("slider_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SliderId", "LanguageId")
                        .IsUnique();

                    b.ToTable("slider_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("degree_type");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("program_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProgramId");

                    b.ToTable("specializations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.SpecializationTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("specialization_id");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SpecializationId", "LanguageId")
                        .IsUnique();

                    b.ToTable("specialization_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Testimonial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("GraduateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("graduate_name");

                    b.Property<int>("GraduateYear")
                        .HasColumnType("int")
                        .HasColumnName("graduate_year");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("media_id");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("specialization_id");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("testimonials", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TestimonialTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("quote");

                    b.Property<Guid>("TestimonialId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("testimonial_id");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TestimonialId", "LanguageId")
                        .IsUnique();

                    b.ToTable("testimonial_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TrainingCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("course_code");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int")
                        .HasColumnName("duration_hours");

                    b.Property<int>("NumberOfSessions")
                        .HasColumnType("int")
                        .HasColumnName("number_of_sessions");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("target_audience");

                    b.Property<Guid>("TrainingCourseCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_course_category_id");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("TrainingCourseCategoryId");

                    b.ToTable("training_courses", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TrainingCourseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("training_course_categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TrainingCourseCategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TrainingCourseCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_course_category_id");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TrainingCourseCategoryId", "LanguageId")
                        .IsUnique();

                    b.ToTable("training_course_category_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TrainingCourseTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("TrainingCourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_course_id");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TrainingCourseId", "LanguageId")
                        .IsUnique();

                    b.ToTable("training_course_translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.IdentityEntity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.IdentityEntity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Admission", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.AdmissionExam", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Admission", "Admission")
                        .WithMany("AdmissionExams")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.AdmissionExamTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.AdmissionExam", "AdmissionExam")
                        .WithMany("Translations")
                        .HasForeignKey("AdmissionExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmissionExam");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.AdmissionResult", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Admission", "Admission")
                        .WithMany("AdmissionResults")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Book", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Media", "CoverImage")
                        .WithMany()
                        .HasForeignKey("CoverImageMediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Media", "BookFile")
                        .WithMany()
                        .HasForeignKey("FileMediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookFile");

                    b.Navigation("CoverImage");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.BookTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Book", "Book")
                        .WithMany("Translations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.CategoryTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Category", "Category")
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Course", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.CourseGroup", "CourseGroup")
                        .WithMany("Courses")
                        .HasForeignKey("CourseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseGroup");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.CourseGroupTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.CourseGroup", "CourseGroup")
                        .WithMany("Translations")
                        .HasForeignKey("CourseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseGroup");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.CourseTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Course", "Course")
                        .WithMany("Translations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Curriculum", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Course", "Course")
                        .WithMany("Curriculum")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Specialization", "Specialization")
                        .WithMany("Curriculum")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Faq", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.FaqCategory", "FaqCategory")
                        .WithMany("Faqs")
                        .HasForeignKey("FaqCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaqCategory");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.FaqCategoryTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.FaqCategory", "FaqCategory")
                        .WithMany("Translations")
                        .HasForeignKey("FaqCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaqCategory");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.FaqTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Faq", "Faq")
                        .WithMany("Translations")
                        .HasForeignKey("FaqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faq");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.LocationTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Location", "Location")
                        .WithMany("Translations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Media", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.MediaCategory", "MediaCategory")
                        .WithMany("Media")
                        .HasForeignKey("MediaCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaCategory");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.MediaCategoryTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.MediaCategory", "MediaCategory")
                        .WithMany("Translations")
                        .HasForeignKey("MediaCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("MediaCategory");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.MenuItem", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Menu", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.MenuItemTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.MenuItem", "MenuItem")
                        .WithMany("Translations")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.PageTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Page", "Page")
                        .WithMany("Translations")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Post", b =>
                {
                    b.HasOne("Domain.Entity.IdentityEntity.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.PostTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Post", "Post")
                        .WithMany("Translations")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.ProgramTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Program", "Program")
                        .WithMany("Translations")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Slider", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.SliderTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Slider", "Slider")
                        .WithMany("Translations")
                        .HasForeignKey("SliderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Slider");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Specialization", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Location", "Location")
                        .WithMany("Specializations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Program", "Program")
                        .WithMany("Specializations")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.SpecializationTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Specialization", "Specialization")
                        .WithMany("Translations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Testimonial", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TestimonialTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.Testimonial", "Testimonial")
                        .WithMany("Translations")
                        .HasForeignKey("TestimonialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Testimonial");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TrainingCourse", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.TrainingCourseCategory", "TrainingCourseCategory")
                        .WithMany("TrainingCourses")
                        .HasForeignKey("TrainingCourseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingCourseCategory");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TrainingCourseCategoryTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.TrainingCourseCategory", "TrainingCourseCategory")
                        .WithMany("Translations")
                        .HasForeignKey("TrainingCourseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TrainingCourseCategory");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TrainingCourseTranslation", b =>
                {
                    b.HasOne("Domain.Entity.ApplicationEntity.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ApplicationEntity.TrainingCourse", "TrainingCourse")
                        .WithMany("Translations")
                        .HasForeignKey("TrainingCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TrainingCourse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entity.IdentityEntity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entity.IdentityEntity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserClaims_AspNetUsers_UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entity.IdentityEntity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserLogins_AspNetUsers_UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entity.IdentityEntity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.IdentityEntity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserRoles_AspNetUsers_UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entity.IdentityEntity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserTokens_AspNetUsers_UserId");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Admission", b =>
                {
                    b.Navigation("AdmissionExams");

                    b.Navigation("AdmissionResults");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.AdmissionExam", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Book", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Category", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Course", b =>
                {
                    b.Navigation("Curriculum");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.CourseGroup", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Faq", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.FaqCategory", b =>
                {
                    b.Navigation("Faqs");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Location", b =>
                {
                    b.Navigation("Specializations");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.MediaCategory", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Menu", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.MenuItem", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Page", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Post", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Program", b =>
                {
                    b.Navigation("Specializations");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Slider", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Specialization", b =>
                {
                    b.Navigation("Curriculum");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.Testimonial", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TrainingCourse", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Domain.Entity.ApplicationEntity.TrainingCourseCategory", b =>
                {
                    b.Navigation("TrainingCourses");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
